[package]
name = "ivxv-decproof-verifier"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
base64 = "0.22.1"
sha2 = "0.11.0-pre.3"
rasn = "0.15.0"
tokio = { version = "1.38.0", features = ["full", "net"] }
futures = "0.3.30"
pem = "3.0.4"
p384 = "0.13.1"
