[package]
name = "ivxv-decproof-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
der = { version = "0.7.9", features = ["oid", "derive", "alloc"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
base64 = "0.22.1"
sha2 = "0.11.0-pre.3"
rug = "1.24.1"
